### ISSUE TITLE
Style Kramdown's syntax highlighter line numbers.

### ISSUE THREAD

**Issue by neizod** [neizod/polar#12]
First, append this into `_config.yml`:

``` yml
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
```

(or find other means to enable line number per code block.)

Observe that output HTML wrap `<pre><code>` with  `<table>`, which now render ugly. Try to fix this issue without altering normal `<table>`.
