### ISSUE TITLE
Show author info and also support co-author, editor, illustrator

### ISSUE THREAD

**Issue by neizod** [neizod/polar#26]
Display info of each article's author at the end of the page. Also display more on co-author, editor, and illustrator too!

**Comment by neizod** [comment]
In `_config.yml`:

``` yaml
author: main_author
```

In front matter yaml of each post:

``` yaml
authors:
  - support_author
  - guess_author
```

In `_data/authors.yml`:

``` yaml
main_author:
  name: name of main author
  bio: short bio of this author
  pic: path/to/main_author_profile_pic.png
support_author:
  name: name of support author
  bio: short bio of this author
  pic: path/to/support_author_profile_pic.png
guess_author:
  name: name of guess author
  bio: short bio of this author
  pic: path/to/guess_author_profile_pic.png
```

Rendering Layout:

```
# Post Title
date, tags

content
content
...
content

---

[ card for author 1 ] [ card for author 2 ]
[ card for author 3 ] [ card for author 4 ]
       [ card for last author (odd) ]

---

comment section
comment 1
comment 2
...
```

Rendering Details:

- Card design, show pic/name/bio of author info
- Card eats up 50% of content width
- Show at most 2 authors per line, last line align card to center
- If no `authors:` provided at front matter yaml, use `config.author` as a default
- If no author info in `_data/authors.yml`, show provided name as-is (with placeholder profile pic)
